server:
  address: 0.0.0.0
  port: 29995
  http2:
    enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.16.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "jokowi"
    bufferDurationMs: 400
    frameBufferDurationMs: 1000
    gcWarnings: true
    opusEncodingQuality: 5
    playerUpdateInterval: 5
    resamplingQuality: MEDIUM
    soundcloudSearchEnabled: true
    youtubeSearchEnabled: true
    youtubePlaylistLoadLimit: 6
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    filters:
      equalizer: true
      volume: true
      timescale: true
      channelMix: true
      distortion: true
      karaoke: true
      lowPass: true
      rotation: true
      tremolo: true
      vibrato: true
    sources:
      bandcamp: true
      http: true
      local: false
      nico: false
      soundcloud: true
      twitch: false
      vimeo: false
      youtube: false

plugins:
  youtube:
    enabled: true
    pot:
      token: "MnhT2vfKOIPrGlPmfGCghVao7Op9y51JxlDz5GbOOSKgXodzmFYTQ_Lg-lyGH552S5ymgQPlMQsX2g9NFyGq32sQ9PA6DLqLkcU5gSWNpdFNkxLUnYmeAzQqBYiYJ8asxVcn98xzcx3QEByRU225fAlDyyky7WKwUOU="
      visitorData: "CgtWSG51Z0ViNkNjbyiRtY3HBjIKCgJJThIEGgAgag=="

lavasrc:
  providers:
    - "spsearch:%QUERY%"
    - "ytmsearch:\"%ISRC%\""
    - "ytmsearch:%QUERY%"
  sources:
    spotify: true
    applemusic: false
    deezer: false
    flowerytts: false
    yandexmusic: false
  spotify:
    clientId: "e311e16239d2491fb6c91f90facb0371"
    clientSecret: "cb3f5ae4c54542d09528c07318ba8060"
    countryCode: "US"
    playlistLoadLimit: 6
    albumLoadLimit: 6

logging:
  level:
    root: INFO
    lavalink: INFO
  file:
    path: ./logs/
  logback:
    rollingPolicy:
      maxFileSize: 100MB
      maxHistory: 7
  request:
    enabled: false
    includeClientInfo: false
    includeHeaders: false
    includePayload: false
    includeQueryString: false

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""
  environment: ""
